/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ShellnutsCardProp } from "./components/shellnuts-card/shellnuts-card";
import { ShellnutsHeaderProps } from "./components/shellnuts-header/shellnuts-header";
export namespace Components {
    interface ShellnutsCard {
        "cardProp": ShellnutsCardProp;
    }
    interface ShellnutsFooter {
    }
    interface ShellnutsHeader {
        "default": boolean;
        "headerProp": ShellnutsHeaderProps;
    }
    interface ShellnutsModal {
        "title": string;
        "visible": boolean;
    }
}
declare global {
    interface HTMLShellnutsCardElement extends Components.ShellnutsCard, HTMLStencilElement {
    }
    var HTMLShellnutsCardElement: {
        prototype: HTMLShellnutsCardElement;
        new (): HTMLShellnutsCardElement;
    };
    interface HTMLShellnutsFooterElement extends Components.ShellnutsFooter, HTMLStencilElement {
    }
    var HTMLShellnutsFooterElement: {
        prototype: HTMLShellnutsFooterElement;
        new (): HTMLShellnutsFooterElement;
    };
    interface HTMLShellnutsHeaderElement extends Components.ShellnutsHeader, HTMLStencilElement {
    }
    var HTMLShellnutsHeaderElement: {
        prototype: HTMLShellnutsHeaderElement;
        new (): HTMLShellnutsHeaderElement;
    };
    interface HTMLShellnutsModalElement extends Components.ShellnutsModal, HTMLStencilElement {
    }
    var HTMLShellnutsModalElement: {
        prototype: HTMLShellnutsModalElement;
        new (): HTMLShellnutsModalElement;
    };
    interface HTMLElementTagNameMap {
        "shellnuts-card": HTMLShellnutsCardElement;
        "shellnuts-footer": HTMLShellnutsFooterElement;
        "shellnuts-header": HTMLShellnutsHeaderElement;
        "shellnuts-modal": HTMLShellnutsModalElement;
    }
}
declare namespace LocalJSX {
    interface ShellnutsCard {
        "cardProp"?: ShellnutsCardProp;
    }
    interface ShellnutsFooter {
    }
    interface ShellnutsHeader {
        "default"?: boolean;
        "headerProp"?: ShellnutsHeaderProps;
    }
    interface ShellnutsModal {
        /**
          * The last name
         */
        "onClicked"?: (event: CustomEvent<boolean>) => void;
        "title"?: string;
        "visible"?: boolean;
    }
    interface IntrinsicElements {
        "shellnuts-card": ShellnutsCard;
        "shellnuts-footer": ShellnutsFooter;
        "shellnuts-header": ShellnutsHeader;
        "shellnuts-modal": ShellnutsModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shellnuts-card": LocalJSX.ShellnutsCard & JSXBase.HTMLAttributes<HTMLShellnutsCardElement>;
            "shellnuts-footer": LocalJSX.ShellnutsFooter & JSXBase.HTMLAttributes<HTMLShellnutsFooterElement>;
            "shellnuts-header": LocalJSX.ShellnutsHeader & JSXBase.HTMLAttributes<HTMLShellnutsHeaderElement>;
            "shellnuts-modal": LocalJSX.ShellnutsModal & JSXBase.HTMLAttributes<HTMLShellnutsModalElement>;
        }
    }
}
